# Generated by Django 5.2.6 on 2025-09-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='per_hour_rate',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=8, verbose_name='Per Hour Rate'),
        ),
    ]
