# Generated by Django 5.1.4 on 2025-09-30 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_payroll', '0004_location_locationattendance_userlocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationAttendance',
        ),
    ]
