# Generated by Django 5.1.4 on 2025-09-30 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_payroll', '0005_delete_locationattendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='attendance_type',
            field=models.CharField(blank=True, choices=[('IN', 'Check-in'), ('OUT', 'Check-out')], help_text='Check-in or Check-out type', max_length=3, null=True, verbose_name='Attendance Type'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='device_info',
            field=models.TextField(blank=True, help_text='Mobile device information', null=True, verbose_name='Device Info'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance from location center in kilometers', max_digits=8, null=True, verbose_name='Distance (km)'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address from which attendance was marked', null=True, verbose_name='IP Address'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='is_within_radius',
            field=models.BooleanField(default=False, help_text='Whether attendance was marked within location radius', verbose_name='Is Within Radius'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='GPS latitude coordinate', max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location where attendance was marked', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs', to='hr_payroll.location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='GPS longitude coordinate', max_digits=11, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who marked attendance (for mobile attendance)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='source_type',
            field=models.CharField(choices=[('ZK', 'ZKTeco Device'), ('MN', 'Manual'), ('MB', 'Mobile')], default='ZK', max_length=10, verbose_name='Source Type'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['user', 'timestamp'], name='hr_payroll__user_id_c70712_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['location', 'timestamp'], name='hr_payroll__locatio_804882_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['source_type', 'timestamp'], name='hr_payroll__source__76e9f1_idx'),
        ),
    ]
