# Generated by Django 5.2.6 on 2025-09-30 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_payroll', '0006_attendancelog_attendance_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who marked attendance (for mobile attendance)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
