# Generated by Django 5.2.6 on 2025-10-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_payroll', '0007_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='location_name',
            field=models.TextField(blank=True, help_text='Location device information', null=True, verbose_name='Location Name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='attendance_bonus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Attendance Bonus'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_account_no',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Bank Account No'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='conveyance_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Conveyance Allowance'),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='employee',
            name='festival_bonus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Festival Bonus'),
        ),
        migrations.AddField(
            model_name='employee',
            name='food_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Food Allowance'),
        ),
        migrations.AddField(
            model_name='employee',
            name='house_rent_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='House Rent Allowance'),
        ),
        migrations.AddField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(blank=True, null=True, verbose_name='Joining Date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='loan_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Loan Deduction'),
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Marital Status'),
        ),
        migrations.AddField(
            model_name='employee',
            name='medical_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Medical Allowance'),
        ),
        migrations.AddField(
            model_name='employee',
            name='nid',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='National ID'),
        ),
        migrations.AddField(
            model_name='employee',
            name='payment_method',
            field=models.CharField(default='Cash', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='employee',
            name='provident_fund',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Provident Fund'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tax_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tax Deduction'),
        ),
    ]
