# Generated by Django 5.2.6 on 2025-10-08 20:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_payroll', '0009_payrollcycle_payrollrecord_payrollpayment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='basic_salary',
        ),
        migrations.AddField(
            model_name='employee',
            name='base_salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text="The employee's basic monthly gross salary.", max_digits=10, null=True, verbose_name='Basic Salary (Monthly)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='attendance_bonus',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Attendance Bonus'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='conveyance_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Conveyance Allowance'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='expected_working_hours',
            field=models.FloatField(blank=True, default=8.0, help_text='Daily contractual working hours (e.g., 8.0)', null=True, verbose_name='Expected Working Hours (Daily)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='festival_bonus',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Festival Bonus'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='food_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Food Allowance'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='house_rent_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='House Rent Allowance'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='loan_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Loan Deduction'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='medical_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Medical Allowance'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='overtime_grace_minutes',
            field=models.IntegerField(blank=True, default=15, null=True, verbose_name='Overtime Grace Minutes'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='overtime_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Explicitly set fixed rate for overtime.', max_digits=8, null=True, verbose_name='Overtime Rate (per hour)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='payment_method',
            field=models.CharField(blank=True, default='Cash', max_length=20, null=True, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='per_hour_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('30.00'), help_text='Explicitly set rate for hourly attendance/calculations.', max_digits=8, null=True, verbose_name='Per Hour Rate'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='provident_fund',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Provident Fund'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tax_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Tax Deduction'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Linked Django user account for login/mobile attendance (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_user', to=settings.AUTH_USER_MODEL, verbose_name='System User Account'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='zkteco_id',
            field=models.CharField(blank=True, help_text='Employee ID used in the ZKTeco attendance machine (optional)', max_length=50, null=True, unique=True, verbose_name='ZKTeco ID'),
        ),
    ]
