# Generated by Django 5.2.6 on 2025-10-09 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_payroll', '0010_remove_employee_basic_salary_employee_base_salary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Branch'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Bio/Description'),
        ),
        migrations.AddField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True, verbose_name='Blood Group'),
        ),
        migrations.AddField(
            model_name='employee',
            name='confirmation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Confirmation Date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Emergency Contact'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Emergency Contact Name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Emergency Contact Relation'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('active', 'Active'), ('probation', 'Probation'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('resigned', 'Resigned')], default='active', max_length=20, verbose_name='Employment Status'),
        ),
        migrations.AddField(
            model_name='employee',
            name='experience',
            field=models.TextField(blank=True, null=True, verbose_name='Previous Experience'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='employee',
            name='highest_education',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Highest Education'),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_type',
            field=models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('CT', 'Contract'), ('IN', 'Internship'), ('TP', 'Temporary')], default='FT', max_length=2, verbose_name='Job Type'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passing_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Passing Year'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Passport Number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_address',
            field=models.TextField(blank=True, null=True, verbose_name='Permanent Address'),
        ),
        migrations.AddField(
            model_name='employee',
            name='present_address',
            field=models.TextField(blank=True, null=True, verbose_name='Present Address'),
        ),
        migrations.AddField(
            model_name='employee',
            name='resignation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Resignation Date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma separated list of skills', null=True, verbose_name='Skills'),
        ),
        migrations.AddField(
            model_name='employee',
            name='termination_date',
            field=models.DateField(blank=True, null=True, verbose_name='Termination Date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='university',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='University/Institution'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=20, null=True, verbose_name='Marital Status'),
        ),
    ]
