# Generated by Django 5.2.6 on 2025-10-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_payroll', '0012_complaint_employeedocument_notice_overtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedocument',
            name='file_path',
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(blank=True, help_text='Upload document file (PDF, DOC, DOCX, JPG, PNG)', max_length=500, null=True, upload_to='employee_documents/%Y/%m/%d/', verbose_name='Document File'),
        ),
    ]
