# Generated by Django 5.2.6 on 2025-10-17 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_supervisor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectRole',
        ),
    ]
