# Generated by Django 5.2.6 on 2025-10-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_owner_task_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='location_restricted',
            field=models.BooleanField(default=True, help_text='If enabled, employees must be within location radius to mark attendance', verbose_name='Location Restricted'),
        ),
    ]
