# Generated by Django 5.1.4 on 2025-09-23 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_alter_userprofile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_type',
        ),
    ]
