# Generated by Django 5.2.6 on 2025-10-17 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_delete_projectrole'),
        ('hr_payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_type', models.CharField(max_length=100, verbose_name='Bonus Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('bonus_date', models.DateField(verbose_name='Bonus Date')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='hr_payroll.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Bonus',
                'verbose_name_plural': 'Bonuses',
                'ordering': ['-bonus_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('installments', models.PositiveIntegerField(verbose_name='Installments')),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Installment Amount')),
                ('application_date', models.DateField(verbose_name='Application Date')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='Approval Date')),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('APP', 'Approved'), ('REJ', 'Rejected'), ('PAI', 'Paid')], default='PEN', max_length=3, verbose_name='Status')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='hr_payroll.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Employee Advance',
                'verbose_name_plural': 'Employee Advances',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Basic Salary')),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gross Salary')),
                ('total_earnings', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Earnings')),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Deductions')),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Net Salary')),
                ('working_days', models.PositiveIntegerField(default=0, verbose_name='Working Days')),
                ('present_days', models.PositiveIntegerField(default=0, verbose_name='Present Days')),
                ('absent_days', models.PositiveIntegerField(default=0, verbose_name='Absent Days')),
                ('leave_days', models.PositiveIntegerField(default=0, verbose_name='Leave Days')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Overtime Hours')),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Overtime Amount')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bonus')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_salaries', to='hr_payroll.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Employee Salary',
                'verbose_name_plural': 'Employee Salaries',
                'ordering': ['-salary_month__year', '-salary_month__month', 'employee__name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(verbose_name='Effective Date')),
                ('basic_salary', models.DecimalField(decimal_places=2, help_text='Base salary amount', max_digits=10, verbose_name='Basic Salary')),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, help_text='Total including earnings', max_digits=10, verbose_name='Gross Salary')),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, help_text='After deductions', max_digits=10, verbose_name='Net Salary')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Earnings')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Deductions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_salary_structure', to='hr_payroll.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Employee Salary Structure',
                'verbose_name_plural': 'Employee Salary Structures',
                'ordering': ['employee__name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('component_type', models.CharField(choices=[('EARN', 'Earning'), ('DED', 'Deduction')], max_length=4, verbose_name='Type')),
                ('is_taxable', models.BooleanField(default=True, verbose_name='Taxable')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Salary Component',
                'verbose_name_plural': 'Salary Components',
                'ordering': ['component_type', 'name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SalaryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.salarycomponent', verbose_name='Component')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='payroll.employeesalary', verbose_name='Salary')),
            ],
            options={
                'verbose_name': 'Salary Detail',
                'verbose_name_plural': 'Salary Details',
                'ordering': ['component__component_type', 'component__name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('month', models.PositiveIntegerField(verbose_name='Month')),
                ('is_generated', models.BooleanField(default=False, verbose_name='Generated')),
                ('generated_date', models.DateTimeField(blank=True, null=True, verbose_name='Generated Date')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Company')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Generated By')),
            ],
            options={
                'verbose_name': 'Salary Month',
                'verbose_name_plural': 'Salary Months',
                'ordering': ['-year', '-month'],
                'unique_together': {('company', 'year', 'month')},
            },
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='salary_month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_salaries', to='payroll.salarymonth', verbose_name='Salary Month'),
        ),
        migrations.AlterUniqueTogether(
            name='employeesalary',
            unique_together={('salary_month', 'employee')},
        ),
        migrations.CreateModel(
            name='SalaryStructureComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed amount for this component', max_digits=10, null=True, verbose_name='Fixed Amount')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of basic/gross salary', max_digits=5, null=True, verbose_name='Percentage')),
                ('calculated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Calculated Amount')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.salarycomponent', verbose_name='Component')),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_components', to='payroll.employeesalarystructure', verbose_name='Salary Structure')),
            ],
            options={
                'verbose_name': 'Salary Structure Component',
                'verbose_name_plural': 'Salary Structure Components',
                'ordering': ['component__component_type', 'component__name'],
                'unique_together': {('salary_structure', 'component')},
            },
        ),
    ]
